#import '../fragments/cateringOrderItem.gql'

fragment CateringOrderFragment on CateringOrder {
  id
  description
  items {
    ...CateringOrderItemFragment
  }
  deliveryDate
  headCount
  phoneNumber
  orderBy
  orderFor
  orderDate
  isTaxable
  tax
  shipToName
  shipToAddress
  billToName
  billToAddress
  isCashOrder
  chargeNumber
  periodEnd
  createdAt
  updatedAt
}
