#import './unit.gql'

fragment EmployeeFragment on Employee {
  id
  firstName
  lastName
  units {
    ...UnitFragment
  }
  salaryBase
  salaryOvertime
  stateTaxCode
  localTaxCode
  isHourly
  isExempt
  isProdEligible
  isActive
  createdAt
  updatedAt
}
