#import './unit.gql'
#import './purchaseCharge.gql'
#import './vendor.gql'

fragment PurchaseFragment on Purchase {
  id
  number
  date
  vendor {
    ...VendorFragment
  }
  unit {
    ...UnitFragment
  }
  items {
    ...PurchaseChargeFragment
  }
}
