#import './unit.gql'

fragment RegisterFragment on Register {
  id
  code
  name
  isActive
  resetNonResetable
  bank
  nonResetable
  commission
  registerType {
    id
    name
  }
  unit {
    ...UnitFragment
  }
  createdAt
  updatedAt
}
