#import '../fragments/city.gql'
#import '../fragments/state.gql'

query Cities($first: Int!, $page: Int!) {
  cities(first: $first, page: $page) {
    paginatorInfo {
      lastPage
    }
    data {
      ...CityFragment
      state {
        ...StateFragment
      }
    }
  }
}
