#import '../fragments/glAccount.gql'

query GlAccounts {
  glAccounts {
    data {
      ...GlAccountFragment
      # parent {
      #   id
      #   name
      # }
      # child {
      #   id
      #   name
      # }
    }
  }
}
