#import '../fragments/glAccount.gql'

query GlAccounts($search: String) {
  glAccounts(name: $search) {
    ...GlAccountFragment
    parent {
      id
      name
    }
    child {
      id
      name
    }
  }
}
