query InventoryCategoryList($page: Int!) {
  inventoryCategoryList(page: $page) {
    paginatorInfo {
      count
      perPage
      total

      firstItem
      lastItem

      currentPage
      lastPage
      hasMorePages
    }
    data {
      id
      itemId
      name
      vending
      glAccount {
        id
        name
      }
    }
  }
}
