#import '../fragments/vendor.gql'
#import '../fragments/term.gql'

query VendorList($page: Int!) {
  vendorList(page: $page) {
    paginatorInfo {
      count
      perPage
      total
      
      firstItem
      lastItem
      
      currentPage
      lastPage
      hasMorePages
    }
    data {
        ...VendorFragment
    }
  }
}
